### ISSUE TITLE
Link Depth

### ISSUE THREAD

**Issue by pierre-pizzetta** [bartdag/pylinkvalidator#1]
Do you think it'd be possible to have an additional parameter to define the link depth the crawler goes to?
like --depth=2 would only follow 2 pages deep.
Could be usefull if there was a page ready with all the url one wants to crawl, or do a quicker pass on a big website.

**Comment by bartdag** [comment]
If I understand correctly, that would be a generalization of the --run-once flag (only crawls the first page)?

**Comment by pierre-pizzetta** [comment]
Yes exactly, current --run-once would be something like --depth=0 (or --depth=1)

**Comment by bartdag** [comment]
Ok, I'll see what I can do.

**Comment by pierre-pizzetta** [comment]
Thanks, great tool by the way!

**Comment by DmytroSoroka** [comment]
Hello,

any news on this? We'd like to give it a shot, but it takes too long to go through the whole website.. hence the "depth" is needed.

D

**Comment by bartdag** [comment]
Hi, my open source time is currently committed to moving my other project, Py4J, far far away from sourceforge, but I'll see if I can implement this quickly tomorrow morning.

**Comment by bartdag** [comment]
I created a branch with the depth option. --run-once == depth=0. I'll try to write the tests tomorrow and merge the branch. I don't think I'll be able to do an official release before the weekend though. Hope this helps!

**Comment by bartdag** [comment]
Here you go. Merged and released (pylinkvalidator 0.2)

**Comment by pierre-pizzetta** [comment]
Thanks we started to use it recently and it's exactly what we needed!
