### ISSUE TITLE
Fork from mtlevolio?

### ISSUE THREAD

**Issue by DerekChia** [bartdag/pylinkvalidator#15]
Hey i came across this link here https://github.com/mtlevolio/pylinkchecker. Just want to know if your version is a fork from this? Thanks.

**Comment by bartdag** [comment]
Yes, this is a fork as mentioned in the license: https://github.com/bartdag/pylinkvalidator/blob/master/LICENSE.txt#L30

I added a few major features after the fork.

Thanks for asking
