### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by DonRichards** [bartdag/pylinkvalidator#26]
Just installed and my first test says this. Tried this as http & https with the exact same response. 

```terminal
$ pylinkvalidate.py --progress http://www.cnn.com/
Starting crawl...
error - http://www.cnn.com/ (1 of 1 - 100%)
Crawling Done...

ERROR Crawled 1 urls with 1 error(s) in 0.11 seconds

  Start URL(s): http://www.cnn.com/

  error (<class 'urllib.error.URLError'>): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>: http://www.cnn.com/


# A little ENV info on my OSX machine.
$ which python
/usr/local/bin/python

$ python --version
Python 3.6.4
```

**Comment by arunelias** [comment]
My work around in dev environment is create a new .py file with following modified code:

from pylinkvalidator import crawler

import requests
requests.packages.urllib3.disable_warnings()

import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

if __name__ == "__main__":
    crawler.execute_from_command_line()

---
Credits to https://gist.github.com/michaelrice/a6794a017e349fc65d01

**Comment by DonRichards** [comment]
Thanks
