### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by jimpriest** [bartdag/pylinkvalidator#6]
Any suggestions for how I could speed this up?  Anything I could optimize code wise?

Currently I'm scanning about 250,000 urls and with 10 workers it takes about 12-13 hrs :)

I know I can increase workers but then I increase traffic which I can't do.

**Comment by bartdag** [comment]
Hi Jim,

I performed around 75 tests on a few sites and there are many variables that can impact performance. Rule of thumb, python 2, lxml, process mode, --prefer-server-encoding, and as many workers as you can tolerate will provide the best performance.

I created a branch, timereporting, that prints two interesting stats:

1. the average response time when the server responds with an HTTP code and not a timeout or an exception.
2. the average process time (will be renamed to parse time) when we can successfully parse a page for links (status code = 200, no exception when parsing)

To give you an idea, when processing nginx.org with depth = 2:

```bash
$ ./pylinkvalidator/bin/pylinkvalidate.py --prefer-server-encoding --depth 2 --parser lxml --header="User-Agent: Mozilla/5.0" --mode process --workers 10 http://nginx.org/
SUCCESS Crawled 1155 urls in 27.46 seconds
  average response time: 0.20 seconds
  average process time: 0.17 seconds
```

Your timings indicate that your crawl is roughly 10 times slower than this. I can try to improve these timings by profiling pylinkvalidator, but I doubt I'll get a major speed boost (but who knows). I also think that a "pause/resume" feature would be useful for large crawls like yours.

In the meantime, if you could provide me with the number of timeouts and the average response and process time, that would be very helpful in determining where to start profiling to get the biggest performance gain.

**Comment by jimpriest** [comment]
Excellent!   I'm using LXML and process. Not sure if I enabled --prefer-server-encoding. Will try that and also try your new branch w/timings. Will try to do that one evening this week and will report back my findings.
